- type: replace
  path: /releases/name=bosh-hm-forwarders?
  value:
    name: bosh-hm-forwarders
    version: latest

- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value:
    name: bosh-hm-forwarder-cloudwatch
    release: bosh-hm-forwarders
    properties:
      access_key_id: ((access_key_id))
      secret_access_key: ((secret_access_key))
      region: ((region))
