- type: replace
  path: /releases/name=bosh-hm-forwarders?
  value:
    name: bosh-hm-forwarders
    version: latest

- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value:
    name: bosh-hm-forwarder-datadog
    release: bosh-hm-forwarders
    properties:
      api_key: ((datadog_api_key))
